### ISSUE TITLE
Test before_all hook Start Horizon Server expecting token secret?

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#355]
Currently botching the server tests

```
<testcase classname="Horizon Server" name=""before all" hook: Start Horizon Server" time="0">
  <failure>
    <![CDATA[
    No token_secret set! Try setting it in .hz/config.toml or passing it to the Server constructor. Error: No token_secret set! Try setting it in .hz/config.toml or passing it to the Server constructor. at new Auth  (src/auth.js:39:13) at new Server (src/server.js:78:18) at Server.&lt;anonymous&gt; (test/utils.js:104:22) at emitListeningNT (net.js:1257:10)
]]>
  </failure>
</testcase>
```

**Comment by deontologician** [comment]
ping @dalanmiller is this still happening?
