### ISSUE TITLE
Express server examples outdated.

### ISSUE THREAD

**Issue by jacekjagiello** [rethinkdb/horizon#394]
Hey everyone,
I am trying extend Express with Horizon, to get stand alone server.

Here's my `backend.js` file

```
#!/usr/bin/env node
'use strict'

const express = require('express')();
const horizon = require('@horizon/server');

const app = express();
const http_server = app.listen(8181);
const horizon_server = horizon(http_server);

console.log('Listening on port 8181.');
```

But when I run this script, it fails: 

```
(...)/node_modules/finalhandler/index.js:58
    var status = res.statusCode
                    ^

TypeError: Cannot read property 'statusCode' of undefined
    at (...)/node_modules/finalhandler/index.js:58:21
    at EventEmitter.handle ((...)/node_modules/express/lib/application.js:169:5)
    at app ((...)/node_modules/express/lib/express.js:38:9)
    at Object.<anonymous> ((...)/backend.js:7:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

I am using latest node version - `6.1.0`. I've also try to run it on `5.10.1`, but error still appears.
Maybe examples are outdated? Or is it problem with my code?

**Comment by triniwiz** [comment]
Try

``` js
#!/usr/bin/env node
'use strict'
const express = require('express');
const horizon = require('@horizon/server');
const app = express();
const http_server = app.listen(3000);
const horizon_server = horizon(http_server,{ auth: { token_secret: 'my_super_secret_secret' } });
```

**Comment by gianpaj** [comment]
I found the issue. Here is the correct code:

``` js
#!/usr/bin/env node
'use strict'

const express = require('express');
const horizon = require('@horizon/server');

const app = express();
const http_server = app.listen(8181);
const horizon_server = horizon(http_server,{ auth: { token_secret: 'my_super_secret_secret' } });

console.log('Listening on port 8181.');
```

There are 2 issues:
1. It should be:
`const express = require('express');`
not
`const express = require('express')();`
2. it's missing auth secret as previously mentioned:
`const horizon_server = horizon(http_server,{ auth: { token_secret: 'my_super_secret_secret' } });`

If you want to get something in the browser you'll need to add something like this before the `app.listen(8181)`:

``` js
app.get('/', function (req, res) {
  res.send('Hello World!');
});
```

**Comment by gianpaj** [comment]
I can make a pull request if the above is correct

**Comment by jacekjagiello** [comment]
Thanks @gianpaj and @triniwiz, now everything works just fine ;)

**Comment by deontologician** [comment]
PRs welcome!
