### ISSUE TITLE
info: Index metadata synced. every second

### ISSUE THREAD

**Issue by stellanhaglund** [rethinkdb/horizon#410]
when adding the new npm package to my server I get `info: Index metadata synced.` every second in my console.

and I have to require it using 

`const horizon = require('./node_modules/horizon/node_modules/@horizon/server');``

`const horizon = require('horizon-server')` is not working

**Comment by flipace** [comment]
Do you also get an error after the metadata log? I also had this and i had to add "project_name: 'dbname'" to the server options.

Also, you might want to require the submodules directly like require('@horizon/server') - at least thats what i do and it works well.

**Comment by stellanhaglund** [comment]
`Cannot find module '@horizon/server'``

I have added project_name to

**Comment by stellanhaglund** [comment]
Now I don't get those messages anymore instead I get

`Unhandled rejection ReqlRuntimeError: Connection is closed in:
r.db("rethinkdb").table("table_config").filter({"db": "idly"}).pluck("name", "indexes").changes({"squash": true, "includeInitial": true, "includeStates": true, "includeTypes": true})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at ReqlRuntimeError.ReqlError [as constructor] (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlRuntimeError (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/errors.js:90:51)
    at mkErr (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/util.js:177:10)
    at Feed.IterableResult._addResponse (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/cursor.js:75:27)
    at TcpConnection.<anonymous> (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/net.js:360:22)
    at TcpConnection.cancel (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/util.js:26:16)
    at TcpConnection.cancel (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/net.js:783:43)
    at wrappedCb (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/net.js:270:17)
    at tryCatcher (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/stellanhaglund/Documents/horizon/custom/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by flipace** [comment]
How did you add horizon in your package json? It has to be done like
'@horizon/client': '1.0.1' same for server, to make this work
Am 18.05.2016 7:29 Vorm. schrieb "Stellan Haglund" <notifications@github.com

**Comment by stellanhaglund** [comment]
Oh I will try that, so just `"@horizon/server": "1.0.1"`?

**Comment by stellanhaglund** [comment]
now I can require it the right way but the error is still there

**Comment by stellanhaglund** [comment]
My table already have data in it since before, could that be the issue?

**Comment by flipace** [comment]
Hmm, a blind guess but could you try to add `permissions: false` to the server options. Just to see if that works. That'd mean that it's really related to the latest permissions additions or so

**Comment by stellanhaglund** [comment]
already did that to

**Comment by stellanhaglund** [comment]
```
const koa = require('koa');
const horizon = require('@horizon/server');
const r = require("rethinkdb");
const app = koa();

const http_server = app.listen(8181);

const server = horizon(http_server, {
  rdb_host: "localhost",
  project_name: 'idly',
  auto_create_index: true, // tried with both true and false
  permissions: false,
  auth: {
    allow_unauthenticated: true,
    token_secret: 'my_super_secret_secret'
  }
});

app.use(require('koa-static')(`${__dirname}/dist`));

```

That's my server code

**Comment by flipace** [comment]
okay, then i think your best bet for now is to either play around with the db and see if any modifications can fix it or keep watching this https://github.com/rethinkdb/horizon/issues/401 for updates :/

**Comment by stellanhaglund** [comment]
okay

**Comment by deontologician** [comment]
ping @Tryneus

**Comment by stellanhaglund** [comment]
This doesnt show up for me anymore, so i dont think its an active issue

**Comment by deontologician** [comment]
Thanks for the update @stellanhaglund

**Comment by davidroman0O** [comment]
Hi,

I still got the same error on horizon 1.1.1, rehtinkdb 2.3.4, node 6 with importing horizon into my express project on OS X. 

I call horizon this way : 

```
const httpServer = app.listen(config.port, () => {
  console.log('server launched');
  const options = { 
   rdb_host: 'localhost', 
   project_name: 'horizon', 
   auto_create_index: false,
   permissions: false, 
   auth: { 
    token_secret: 'my_super_secret_secret', 
   } 
 }; 
 require('@horizon/server')(httpServer, options);
});
```

I got a lot of "info: Index metadata synced." every seconds.

I didn't find a lot of documentation about this. :/

**Comment by danielmewes** [comment]
Re-opening as it still seems to be an issue.

**Comment by deontologician** [comment]
Need verification this is happening in 2.x.x
