### ISSUE TITLE
"auto_create_table" is not allowed

### ISSUE THREAD

**Issue by aihornmac** [rethinkdb/horizon#442]
After upgrading from

```
"@horizon/client": "0.1.0",
"@horizon/server": "0.1.1-0",
```

to

```
"@horizon/client": "1.0.1",
"@horizon/server": "1.0.1",
```

the following error occurs

```
project/node_modules/joi/lib/index.js:137
                throw error;
                ^

ValidationError: {
  "auto_create_index": true,
  "auth": {
    "allow_anonymous": true,
    "allow_unauthenticated": true,
    "token_secret": "a token secret"
  },

  "auto_create_table" [1]: true
}

[1] "auto_create_table" is not allowed
    at Object.exports.process (project/node_modules/joi/lib/errors.js:152:19)
    at internals.Any._validateWithOptions (project/node_modules/joi/lib/any.js:661:27)
    at root.validate (project/node_modules/joi/lib/index.js:103:23)
    at root.attempt (project/node_modules/joi/lib/index.js:132:29)
    at new Server (project/node_modules/@horizon/server/src/server.js:62:22)
    at create_server (project/node_modules/@horizon/server/src/horizon.js:8:3)
    at Object.<anonymous> (server.js:18:23)
    at Module._compile (module.js:541:32)
    at loader (project/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (project/node_modules/babel-cli/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
```

Please help! Thank you!

**Comment by danielmewes** [comment]
The argument is now called `auto_create_collection`.

**Comment by aihornmac** [comment]
Thank you for your answering! It's a bit subtle since documentations seems not elaborate, hope there could be more introductions. Anyway, thanks again!

**Comment by aihornmac** [comment]
Then it results in another issue:

```
info: Connecting to RethinkDB: localhost:28015
info: Index metadata synced.
info: Groups metadata synced.
error: Connection to RethinkDB terminated: ReqlDriverCompileError: Argument 1 to table may not be `undefined`.
```

What's this? @danielmewes

**Comment by danielmewes** [comment]
Yeah sorry that documentation is still pretty scarce on this stuff. We'll hopefully be adding a lot more in the next weeks.

The new error sounds like it might be some kind of bug, though I haven't seen this one before.

It might also be an incompatibility with the metadata from 0.1.0 that might still be around in the RethinkDB database. Can you try moving the `rethinkdb_data` directory out of the way and then restarting the RethinkDB server? That should cause it to create a fresh database. It will also lose all the data that might have been stored in your application state, so make sure that you keep the copy of the old rethinkdb_data folder if there's anything important in there.

@Tryneus any idea what else might cause the ReqlDriverCompileError @aihornmac is seeing?

**Comment by danielmewes** [comment]
(re-opening temporarily. If we can't figure out what's causing the new issue, we should rename this though)

**Comment by aihornmac** [comment]
Done it! After removing `rethinkdb_data` directory and restarting rethinkdb, things went right!
