### ISSUE TITLE
Intermittent "Write invalidated by another request, try again." failure in client tests

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#475]
On Horizon 1.0.2, I'm getting this intermittently in the "can subscribe to multiple ids " client tests:

```
Write invalidated by another request, try again.
Error: Write invalidated by another request, try again.
    at Object.t.subscribe.next (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e.__tryOrUnsub (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.notifyNext (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:3:119)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at Object.n [as subscribeToResult] (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e._innerSub (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e._tryNext (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at e.__tryOrUnsub (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:4:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._finalNext (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.__tryOrUnsub (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e._next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at e.next (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at n.&lt;anonymous&gt; (dist/webpack:/webpack/universalModuleDefinition:2:1)
    at n.r.emit (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at n.onPacket (dist/webpack:/webpack/universalModuleDefinition:3:119)
    at n.&lt;anonymous&gt; (dist/webpack:/webpack/universalModuleDefinition:3:119)
    at n.r.emit (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at n.onPacket (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at n.onData (dist/webpack:/webpack/universalModuleDefinition:1:1)
    at WebSocket.ws.onmessage (dist/webpack:/webpack/universalModuleDefinition:3:119)
    at WebSocket.onMessage (node_modules/ws/lib/WebSocket.js:418:14)
    at Receiver.ontext (node_modules/ws/lib/WebSocket.js:816:10)
    at node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (node_modules/ws/lib/Receiver.js:364:5)
    at node_modules/ws/lib/Receiver.js:466:14
    at Receiver.flush (node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.1.finish (node_modules/ws/lib/Receiver.js:482:12)
    at Receiver.expectHandler (node_modules/ws/lib/Receiver.js:457:31)
    at Receiver.add (node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (node_modules/ws/lib/WebSocket.js:800:20)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

@Tryneus

**Comment by deontologician** [comment]
#513 should have fixed this
