### ISSUE TITLE
Collection "react_messages" has no index matching ["datetime"]

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#533]
Reported by @SenerDemiral in https://github.com/rethinkdb/horizon-docs/issues/71#issuecomment-222115746 :
## 

Still 
**Uncaught Error: Collection "react_messages" has no index matching ["datetime"]**

Example react-chat-app
Steps to produce

$ rethinkdb
$ cd reactChat
$ hz set-schema schema.toml

$ hz get-schema

```
# This is a TOML document
[collections.react_messages]
indexes = ["datetime"]
[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"
```

$ hz serve --permissions no 

**Browse localhost:8181**
    Console message
    Uncaught Error: Collection "react_messages" has no index matching ["datetime"]

**RethinkDB Administration Console**
    r.db('reactChat').table('react_messages_17d5d480f158').info()
    returned row

```
{
    "db": {
        "id":  "4348c660-469c-45cb-a4f7-748d25c5a6c1" ,
        "name":  "reactChat" ,
        "type":  "DB"
    } ,
    "doc_count_estimates": [
        24
    ] ,
    "id":  "6a5a7363-20c7-4646-876e-512c593b988d" ,
    "indexes": [
        "datetime"
    ] ,
    "name":  "react_messages_17d5d480f158" ,
    "primary_key":  "id" ,
    "type":  "TABLE"
}
```

**schema.toml file**

```
[collections.react_messages]
indexes = ["datetime"]
```

**config.toml file**

```
bind = [ "localhost" ]
port = 8181
secure = false
project_name = "reactChat"
serve_static = "dist"
auto_create_collection = true
connect = "localhost:28015"
start_rethinkdb = false
debug = true
token_secret = "vpd6iG3Ejfwdo5Fhuv16R3+J6fL69q5skGEkUEgXmb3tYGUy8YMDrwBgrkDeHPX4HKHT5Zrz1KPkhki0R009xA=="
allow_unauthenticated = true
```

**Comment by deontologician** [comment]
Not sure whether this is a bug or intended. @Tryneus is there any way to specify indices in configuration and have the tool create them for you?

**Comment by danielmewes** [comment]
I just reproduced this and there definitely seems to be some bug or inconsistency somewhere.

I followed the steps that @SenerDemiral described and loaded the following schema file initially:

``` toml
# This is a TOML document
[collections.react_messages]
indexes = ["datetime"]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"

[groups.default]
[groups.default.rules.allow_any]
template = "any()"
```

Note that this defines a "datetime" index. `set-schema` also creates this index on the `react_messages` table.
If I then start Horizon with `hz serve reactChat --start-rethinkdb --secure no --allow-unauthenticated --token-secret foo --serve-static ./dist --auto-create-index` (note the _auto-create-index_) and open the page, it works, but the Horizon server still prints the message

```
warn: Auto-creating index on collection "react_messages" (dev mode): ["datetime"]
```

However looking at RethinkDB, it didn't actually add any new index to the table. There's still only one index called `datetime`. Even weirder, if I then restart Horizon without the `--auto-create-index` (but on the same RethinkDB database), things no longer work (debug output):

```
debug: Received request from client: {"type":"subscribe","options":{"collection":"react_messages","order":[["datetime"],"descending"],"limit":8},"request_id":0}
debug: Error on request 0:
Error: Collection "react_messages" has no index matching ["datetime"].
    at IndexMissing (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/error.js:13:10)
    at Collection.get_matching_index (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/collection.js:85:13)
    at order_keys.forEach.eval_key (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/query.js:37:30)
    at order_keys.forEach.reql (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/query.js:77:12)
    at Request.reql.changes.run.then [as _endpoint] (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/subscribe.js:8:16)
    at Request.run (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/request.js:42:30)
    at Client.handle_request (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:162:13)
    at /usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:112:47
    at Client.error_wrap_socket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:55:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:112:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/socket.js:102:14)
    at emitOne (events.js:77:13)
    at XHR.emit (events.js:169:7)
    at XHR.Transport.onPacket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transport.js:104:8)
    at callback (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:208:10)
    at Object.exports.decodePayload (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:298:19)
    at XHR.Polling.onData (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:211:10)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:171:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
debug: Handling error: Collection "react_messages" has no index matching ["datetime"].
debug: Sending error result for request 0:
Error: Collection "react_messages" has no index matching ["datetime"].
    at IndexMissing (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/error.js:13:10)
    at Collection.get_matching_index (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/collection.js:85:13)
    at order_keys.forEach.eval_key (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/query.js:37:30)
    at order_keys.forEach.reql (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/query.js:77:12)
    at Request.reql.changes.run.then [as _endpoint] (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/endpoint/subscribe.js:8:16)
    at Request.run (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/request.js:42:30)
    at Client.handle_request (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:162:13)
    at /usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:112:47
    at Client.error_wrap_socket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:55:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/src/client.js:112:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/socket.js:102:14)
    at emitOne (events.js:77:13)
    at XHR.emit (events.js:169:7)
    at XHR.Transport.onPacket (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transport.js:104:8)
    at callback (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:208:10)
    at Object.exports.decodePayload (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:298:19)
    at XHR.Polling.onData (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:211:10)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/horizon/node_modules/@horizon/server/node_modules/engine.io/lib/transports/polling.js:171:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
debug: Sending response: {"error":"Collection \"react_messages\" has no index matching [\"datetime\"].","error_code":-1,"request_id":0}
```

**Comment by danielmewes** [comment]
It seems like maybe the server isn't initializing the list of existing indexes properly on startup?

**Comment by Tryneus** [comment]
@danielmewes - this appears to be a race in initialization of the metadata.  If the index info arrives before the collection info, the information is lost.  I'll prepare a fix.

**Comment by Youmoo** [comment]
@Tryneus When will this fix be published? Thanks.

**Comment by danielmewes** [comment]
@Youmoo Since today is a holiday in the US, I think you can expect the next release around Wednesday or Thursday. We might have a patch before then that you can apply manually.

**Comment by Tryneus** [comment]
Fix is up in PR #558 - sorry about the delay, @Youmoo!

**Comment by aesedepece** [comment]
I'm suffering this very issue with 1.1.3 :sob: 

`r.db('vault').table('diffs_b758e0b96b52').info()`

``` json
{

    "db": {
        "id": "55d5573b-5f47-47ab-b2f3-9c86e301991e" ,
        "name": "vault" ,
        "type": "DB"
    } ,
    "doc_count_estimates": [
        0
    ] ,
    "id": "b00217eb-be0d-41e8-907e-e18a4d2d5481" ,
    "indexes": [
        "creator" ,
        "datetime" ,
        "reader"
    ] ,
    "name": "diffs_b758e0b96b52" ,
    "primary_key": "id" ,
    "type": "TABLE"
}
```

`Uncaught Error: Collection "diffs" has no index matching ["reader","datetime"].`

**Comment by aesedepece** [comment]
Forget what I said, I'm just an idiot. I was not setting "reader_datetime" index properly. :sweat_smile: 

It simply works with:

``` json
"indexes": [
  "creator",
  "datetime",
  "reader",
  "reader_datetime"
]
```
