### ISSUE TITLE
Error on query with end_subscription

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#651]
Sending the request:

```
debug: Received request from client: {"request_id":624,"type":"subscribe","options":{"collection":"testA","find":{"id":1}}}
debug: Received request from client: {"request_id":624,"type":"end_subscription"}
debug: Error on request 624:
Error: Operation not permitted.
    at feed.eachAsync (/home/josh/Code/horizon/server/src/endpoint/subscribe.js:25:17)
    at userCb (/home/josh/Code/horizon/server/node_modules/rethinkdb/cursor.js:296:31)
    at /home/josh/Code/horizon/server/node_modules/rethinkdb/cursor.js:342:17
    at tryCatcher (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/josh/Code/horizon/server/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
debug: Sending response: {"error":"Operation not permitted.","error_code":-1,"request_id":624}
```

Doesn't cause an issue with the client

**Comment by deontologician** [comment]
This is just a side effect of the way queries are cancelled in horizon, it's never reported to the user, but it'd be nice to avoid throwing the error and sending a message over the network

**Comment by deontologician** [comment]
I've decided this is dumb, so closing
