### ISSUE TITLE
`hz make-token` is broken in `next`

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/horizon#691]
As of 81402f8:

```
$ hz make-token user
/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/make-token.js:56
  config = serve.merge_configs(config, serve.read_config_from_file(parsed.project_path,
                                             ^

TypeError: serve.read_config_from_file is not a function
    at Object.processConfig (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/make-token.js:56:46)
    at runCommand (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/main.js:52:27)
    at Object.<anonymous> (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/main.js:70:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by dalanmiller** [comment]
Should be `serve.read_config_from_secrets_file` as that is where `token_secret` is now stored.

**Comment by danielmewes** [comment]
We should probably have a CLI test for this too.

**Comment by dalanmiller** [comment]
Just ran this using #696 and it now causes this error:

```
$ hz make-token user
error: rethinkdb stderr: warn: Cache size does not leave much memory for server and query overhead (available memory: 1033 MB).
error: Unclean shutdown - killing RethinkDB child process
/Users/dalanmiller/repos/fusion/server/node_modules/rethinkdb/net.js:570
          cache_string = password.toString("base64") + "," + salt.toString("base64") + "," + iterations.toString();
                                 ^

TypeError: Cannot read property 'toString' of null
    at pbkdf2_hmac (/Users/dalanmiller/repos/fusion/server/node_modules/rethinkdb/net.js:570:34)
    at Socket.handshake_callback (/Users/dalanmiller/repos/fusion/server/node_modules/rethinkdb/net.js:656:35)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
```

**Comment by danielmewes** [comment]
Independently of the bug, why does `make-token` even start RethinkDB? Is that actually necessary?

**Comment by deontologician** [comment]
it checks that the user exists. we could skip that step since it doesnt
really need it

**Comment by danielmewes** [comment]
Hmm not sure. Let's leave it in for now.
