### ISSUE TITLE
error in examples

### ISSUE THREAD

**Issue by zwhitchcox** [rethinkdb/horizon#831]
I cloned this repository and tried to run the example for hapi, and I get this error:

```
hapi-server $ node main
module.js:457
    throw err;
    ^

Error: Cannot find module 'horizon-server'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zane/horizon/examples/hapi-server/main.js:5:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

Server version: 2.0.0
Client version: cloned from here

**Comment by zwhitchcox** [comment]
For anyone else confused by this, you have to do `require('@horizon/server')`
